version: "3.8"

services:
  backend:
    build:
      context: ./server
    container_name: avito-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: avito-frontend
    ports:
      - "3000:5173"
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
